// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc810.MecanumDrive;

import com.kauailabs.navx.frc.AHRS;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	
	public static AHRS navX;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainFR;
    public static SpeedController driveTrainFL;
    public static SpeedController driveTrainBR;
    public static SpeedController driveTrainBL;
    public static RobotDrive driveTrainRobotDrive41;
    public static AnalogGyro driveTrainGyro;
    public static Servo cameraPan;
    public static Servo cameraTilt;
    public static AnalogInput cameraUltrasonicsensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainFR = new Victor(0);
        LiveWindow.addActuator("DriveTrain", "FR", (Victor) driveTrainFR);
        
        driveTrainFL = new Victor(1);
        LiveWindow.addActuator("DriveTrain", "FL", (Victor) driveTrainFL);
        
        driveTrainBR = new Victor(2);
        LiveWindow.addActuator("DriveTrain", "BR", (Victor) driveTrainBR);
        
        driveTrainBL = new Victor(3);
        LiveWindow.addActuator("DriveTrain", "BL", (Victor) driveTrainBL);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainFL, driveTrainBL,
              driveTrainFR, driveTrainBR);
        
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        driveTrainGyro = new AnalogGyro(1);
        LiveWindow.addSensor("DriveTrain", "Gyro", driveTrainGyro);
        driveTrainGyro.setSensitivity(0.007);
        cameraPan = new Servo(8);
        LiveWindow.addActuator("Camera", "Pan", cameraPan);
        
        cameraTilt = new Servo(9);
        LiveWindow.addActuator("Camera", "Tilt", cameraTilt);
        
        cameraUltrasonicsensor = new AnalogInput(0);
        LiveWindow.addSensor("Camera", "Ultrasonic sensor", cameraUltrasonicsensor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
       /* navX = new AHRS(Port.kUSB1);
        
        LiveWindow.addSensor("DriveTrain", "Navx", navX);
       AutoPutData.addNumber("Navx", navX::getAngle);
       AutoPutData.addNumber("Velocity X", navX::getVelocityX);
       AutoPutData.addNumber("Velocity Y", navX::getVelocityY);
       AutoPutData.addNumber("Velocity Z", navX::getVelocityZ);
       AutoPutData.addNumber("Displacement X", navX::getDisplacementX);
       AutoPutData.addNumber("Displacement Y", navX::getDisplacementY);
       AutoPutData.addNumber("Displacement Z", navX::getDisplacementZ);*/
       AutoPutData.addNumber("Ultrasonic", ()->cameraUltrasonicsensor.getAverageVoltage()*108.515);
       AutoPutData.addNumber("Camera X", cameraPan::get);
       AutoPutData.addNumber("Camera Y", cameraTilt::get);
       AutoPutData.addNumber("Gyro", driveTrainGyro::getAngle);
       AutoPutData.addNumber("Gyro Rate", driveTrainGyro::getRate);
       //navX.zeroYaw();
      // navX.resetDisplacement();
       driveTrainGyro.reset();
      
    }
}
